name: Invitation to Youth Group - GitHub Organization.
description: Use this template to request an invitation to our organization
title: "[ORG] Invite me to the organization"
labels: [✉️ Invitation]
body:
  - type: markdown
    attributes:
      value: '# Join Our Organization'
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: How did you come to know about Youth Group? What do you like about this community/Why do you want to join?
    validations:
      required: true